### ISSUE TITLE
Font and style not same as Facebook mobile site

### ISSUE THREAD

**Issue by rajgourav** [Bl1xY/mobile-facebook-phishing#1]
hi, your files are working fine. However the design and style of the website is really different fro the Facebook mobile site, can you update this with the latest facebook style?

**Comment by Bl1xY** [comment]
> hi, your files are working fine. However the design and style of the website is really different fro the Facebook mobile site, can you update this with the latest facebook style?

Hi, yes I am aware of this. At the time of build it was correct but I plan to update it. Thanks for the reminder!

**Comment by rajgourav** [comment]
If you are confined home and bored, can you do it soon please... 🙂😉 I'm sure you will not take much time

**Comment by Bl1xY** [comment]
> If you are confined home and bored, can you do it soon please...  I'm sure you will not take much time

Haha I'm confined at work, we have wifi but its area restricted. I will get round to it as soon as possible ✌

**Comment by Bl1xY** [comment]
Updated
